module.exports = {
  ITEM_DROPPED: "ITEM_DROPPED",
  ITEM_DRAG_STARTED: "ITEM_DRAG_STARTED",
  CONTENT_CREATED: "CONTENT_CREATED",
  TASK_COMPLETION_CHANGED: "TASK_COMPLETION_CHANGED",
  TASK_CREATED: "TASK_CREATED"
};